version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - TZ="Asia/Shanghai"
      - LANG="en_US.UTF-8"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
      - ./logs:/logs
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf